---
# tasks file for duply
- name: install
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  with_items: duply_install
  when: duply_install
  tags: [configuration, duply, duply-install]

- name: install
  get_url:
    url: http://sourceforge.net/p/ftplicity/code/43/tree/duply/trunk/duply.sh?format=raw
    dest: "{{ duply_install_dir }}/duply"
    force: true
    owner: root
    group: root
    mode: 0755
  tags: [configuration, duply, duply-install]
