# tasks file for duply
---
- name: install
  apt:
    name: "{{ duply_install }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - duply
    - duply-install

- name: install
  get_url:
    url: "https://raw.githubusercontent.com/Oefenweb/duply/{{ duply_version }}/duply.sh"
    dest: "{{ duply_install_dir }}/duply"
    force: true
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - duply
    - duply-install
